name: Update Forex Rates CSV
on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r streamlit/requirements.txt
      - run: python forexup.py
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/rates.csv
          git commit -m "Auto update forex rates CSV" || echo "No changes to commit"
          git push
