name: Keep Streamlit App Alive (8-min ping)

on:
  schedule:
    - cron: '*/8 * * * *'  # Ping setiap 8 menit UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          echo "=== $(date) ==="
          echo "Start pinging Streamlit app..."

          # check 303 or not
          echo "response:"
          curl -s -D - https://abtabed.streamlit.app -o /dev/null | grep -E "HTTP/|Location:"

          # follow redirect dan ambil status akhir
          echo -n "Final status code: "
          curl -L -s -o /dev/null -w "%{http_code}" https://abtabed.streamlit.app
